Fix: Add missing glue.h include in host.c
The elf_init() function call in host.c requires the glue.h header
to be included for the function prototype. This fixes the compilation
error: 'call to undeclared function elf_init'